### ISSUE TITLE
gamepad

### ISSUE THREAD

**Issue by sa9St** [calico-crusade/PalringoApi#4]
hey 
can you add a method to control gamepad events ?

**Comment by calico-crusade-2** [comment]
Sorry man, gamepad cannot be controlled via the TCP client, you would need to work with either their Socket.IO client (chat.palringo.com) or do direct script mods on their mobile clients

**Comment by sa9St** [comment]
ok , thanks man 

also is there any way to get all the group id's on the account ? i used Isjoin method but it dont give me all the group ids on the account

**Comment by calico-crusade** [comment]
You should be able to use Bot.Information.Groups, it is a dictionary of the groups, with the group ID as the key and the value being a Group object. Sorry about the late reply, I have been sick lately. Feel free to hit me up on pal with further questions. Id: 43681734
